name: insight
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  font_awesome_flutter: ^10.10.0
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.2.0

  # Local Storage
  shared_preferences: ^2.5.3

  # OCR & Image Processing
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.2.0

  # Functional Programming
  dartz: ^0.10.1

  # Date Formatting
  intl: ^0.20.2

  # Permissions (if needed for camera)
  permission_handler: ^12.0.1
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
