// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'insight';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String SHARE_CLASICA = 'assets/images/Share_clasica.jpg';
  static const String SHARE_CLASIFICATORIA = 'assets/images/Share_clasificatoria.jpg';
  static const String SHARE_COLISEO = 'assets/images/Share_coliseo.jpg';
  static const String SHARE_TOTAL = 'assets/images/Share_total.jpg';
}
